
services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ticketing-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./infrastructure/sql/init:/docker-entrypoint-initdb.d
    networks:
      - ticketing-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -Q 'SELECT 1' -C || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  # Elasticsearch for EventSearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: ticketing-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - ticketing-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  # Redis for EventSearch caching
  redis:
    image: redis:7.2-alpine
    container_name: ticketing-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ticketing-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Zookeeper for Kafka coordination
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: ticketing-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_logs:/var/lib/zookeeper/log
    networks:
      - ticketing-network
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Kafka Message Broker
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: ticketing-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 6
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - ticketing-network
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Kafka UI for development and monitoring
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ticketing-kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: ticketing-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      DYNAMIC_CONFIG_ENABLED: "true"
    ports:
      - "8090:8080"
    networks:
      - ticketing-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # EventManagement Service
  eventmanagement-api:
    build:
      context: ./src/backend/EventManagement
      dockerfile: Dockerfile
    container_name: eventmanagement-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=EventManagementDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true;Encrypt=false;
      - EventSearch__BaseUrl=http://eventsearch-api:8080
      - ASPNETCORE_LOGGING__LOGLEVEL__DEFAULT=Information
      - ASPNETCORE_LOGGING__LOGLEVEL__MICROSOFT=Warning
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - ticketing-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # EventSearch Service
  eventsearch-api:
    build:
      context: ./src/backend/EventSearch
      dockerfile: Dockerfile
    container_name: eventsearch-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Elasticsearch=http://elasticsearch:9200
      - ConnectionStrings__Redis=redis:6379
      - ASPNETCORE_LOGGING__LOGLEVEL__DEFAULT=Information
      - ASPNETCORE_LOGGING__LOGLEVEL__MICROSOFT=Warning
      - ASPNETCORE_LOGGING__LOGLEVEL__EVENTSEARCH=Debug
    ports:
      - "8081:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ticketing-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Angular Frontend
  frontend:
    build:
      context: ./src/frontend/ticket-booking-system
      dockerfile: Dockerfile
    container_name: ticket-booking-frontend
    ports:
      - "4200:80"
    depends_on:
      eventmanagement-api:
        condition: service_healthy
      eventsearch-api:
        condition: service_healthy
    networks:
      - ticketing-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Future: TicketInventory Service (ready for when we build it)
  # ticketinventory-api:
  #   build:
  #     context: ./src/backend/TicketInventory
  #     dockerfile: Dockerfile
  #   container_name: ticketinventory-api
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:8080
  #     - CosmosDB__ConnectionString=${COSMOS_CONNECTION_STRING}
  #   ports:
  #     - "5002:8080"
  #   networks:
  #     - ticketing-network

  # Future: PaymentProcessing Service
  # paymentprocessing-api:
  #   build:
  #     context: ./src/backend/PaymentProcessing
  #     dockerfile: Dockerfile
  #   container_name: paymentprocessing-api
  #   ports:
  #     - "5003:8080"
  #   networks:
  #     - ticketing-network

  # Future: NotificationService
  # notificationservice-api:
  #   build:
  #     context: ./src/backend/NotificationService
  #     dockerfile: Dockerfile
  #   container_name: notificationservice-api
  #   ports:
  #     - "5004:8080"
  #   networks:
  #     - ticketing-network

  # Future: API Gateway
  # api-gateway:
  #   build:
  #     context: ./src/backend/APIGateway
  #     dockerfile: Dockerfile
  #   container_name: api-gateway
  #   ports:
  #     - "5000:8080"
  #   networks:
  #     - ticketing-network

networks:
  ticketing-network:
    driver: bridge
    name: ticketing-network

volumes:
  sqlserver_data:
    driver: local
  elasticsearch_data:
    driver: local
  redis_data:
    driver: local
  kafka_data:
    driver: local
  zookeeper_data:
    driver: local
  zookeeper_logs:
    driver: local
